name: svo_filters-3.6
channels:
  - defaults
  - http://ssb.stsci.edu/astroconda
dependencies:
  - astropy=4.2
  - bokeh=2.2.3
  - numpy=1.19.2
  - python=3.6
  - pip:
    - PyYAML>=5.4
    - git+https://github.com/astropy/astroquery.git@ccc96185beeff86f3a12a31a00a801afcebe1dbe
